### ISSUE TITLE
Nuget

### ISSUE THREAD

**Issue by alexpetrou94** [cdiggins/parakeet#1]
Hey there, 😄

Ever thought about turning this library into a NuGet package? 
I'm super interested in tinkering with it, and it looks like it's got what I need.

**Comment by cdiggins** [comment]
Hi @alexpetrou94, yes I have been planning to do that. If you need it, then I might be able to get to doing it this week. 

I moved the parsing code into my main development repository (https://github.com/ara3d/ara3d/tree/main/src) and start calling it "Ara3D.Parsing", where some tweaks and improvements have been happening. I am planning to move that code back into this repository, and just using it as a submodule. The only big change is that the CST generation now happens in its own project.  

What kind of grammar or use-case do you have? Maybe I can help.

**Comment by alexpetrou94** [comment]
Thanks for your quick response! No rush on your end, take your time.

I'm currently working on creating a CSS-like language for the Godot Game Engine (A pet project). The goal is to make styling the UI more intuitive. Right now, I'm manually parsing text, which isn't the most efficient approach. In my search for a simpler parsing solution, I came across Parakeet, and it looks like it could be an ideal.

**Comment by cdiggins** [comment]
Hi @alexpetrou94 , I have just posted the most recent version of my parsing library to nuget at https://www.nuget.org/packages/Ara3D.Parsing/1.0.0. There are a few changes from Parakeet. The CST generation code has been moved out into a separate project: https://github.com/ara3d/ara3d/tree/main/src/Ara3D.Parsing.CST.

**Comment by alexpetrou94** [comment]
Thank you for the update! I'll definitely check it out and play around with the NuGet package. 😄

**Comment by cdiggins** [comment]
Hello @alexpetrou94 , just a head's up that I have been doing some work on Parakeet. I restructured the project, went back to branding it Parakeet (instead of "Ara3D.Parsing"), and started work on creating some new grammars, including a CSS one (which is currently untested). The work is currently in the repository, and not yet on the Nuget. I am traveling, so it will be a couple of weeks before I get the new version fully tested and back on Nuget.

**Comment by alexpetrou94** [comment]
Hey @cdiggins.

Thanks for the heads up on the Parakeet updates! 
I've been playing around with the library, and gotta say, the demos make it a breeze to understand. I managed to get the CSS-like grammar I wanted, but I will have a look at the new demo. I will also start playing around with the code generation in the next couple of days and see if I need it or not. While you're on the road, I'm planning to clone the repo and reference the project directly until the Nuget version is all set.

Enjoy your travels. 😄

**Comment by cdiggins** [comment]
Hi @alexpetrou94, I've made a new update on Nuget, and I've changed the name: Check out: https://www.nuget.org/packages/Ara3D.Parakeet.

**Comment by alexpetrou94** [comment]
Hello @cdiggins , 
I will check it out, thank you very much. 😄
